### ISSUE TITLE
Get rid of "Properties" in the module names.

### ISSUE THREAD

**Issue by adithyaov** [composewell/unicode-data#17]
Keep the module names short. `Properties` is implied anyway and does not provide any useful information.

**Comment by harendra-kumar** [comment]
We are using `Streamly.Unicode` for unicode ops in streamly, if we unify that with `Unicode` in this module then we should make it `Unicode.UCD.*` to differentiate UCD from other high level modules under `Streamly.Unicode`. Basically replace `Properties` with `UCD`, as we can have anything from http://www.unicode.org/Public/UCD/latest/ucd/ under this module.

**Comment by adithyaov** [comment]
I'm thinking of this as a more general module. This should not be constrained with the nomenclature of Streamly (or should it?). So, instead of `Unicode.UCD.*`, I propose `UCD.*`.
