### ISSUE TITLE
Rename "DecomposeHangul"?

### ISSUE THREAD

**Issue by adithyaov** [composewell/unicode-data#18]
Possible renaming schemes:
1. Rename `DecomposeHangul` to `Decompose.Hangul`
2. Move `decomposeCharHangul` to `Decompose` and rename `DecomposeHangul` to just `Hangul`

**Comment by harendra-kumar** [comment]
The second option sounds better because `decomposeCharHangul` is not just for decompostion, a comment in it says:

```
-- General utilities used by decomposition as well as composition
```
