### ISSUE TITLE
Module and API naming

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/unicode-data#27]
Module structure:

* Unicode.Char: re-export all the modules

* Unicode.Char.Normalization
    * Compose
    * Decompose
    * CombiningClass
* Unicode.Char.General:
    * isAlpha
    * isSpace
    * Hangul
* Unicode.Char.Case
    * isLower
    * isUpper

* Unicode.Internal.Generated => Unicode.Internal.Char

Function naming:

* isSecondStarter => isCombiningStarter
* isAlpha => isLetter

**Comment by adithyaov** [comment]
Few thoughts:
- Is `Unicode.Char.Case` going to have any more functions? A module with only 2 functions? `Case` seems very specific.
- I prefer `Unicode.Internal.Generated.Char` over `Unicode.Internal.Char`. `Unicode.Internal.Char` gives a false sense of just re-exporting (mirroring the structure), like how we do it in Streamly.

**Comment by harendra-kumar** [comment]
> Is Unicode.Char.Case going to have any more functions? A module with only 2 functions? Case seems very specific.
The module org follows this: https://www.unicode.org/reports/tr44/#Property_Index_Table as I mentioned in the README update in the PR.

> I prefer Unicode.Internal.Generated.Char over Unicode.Internal.Char. Unicode.Internal.Char gives a false sense of just re-exporting (mirroring the structure), like how we do it in Streamly.

That's a very specific intuition because you have worked on streamly. We can make it `Unicode.Internal.UCD` instead. That will rightly indicate that this is all directly from UCD.

**Comment by adithyaov** [comment]
> The module org follows this: https://www.unicode.org/reports/tr44/#Property_Index_Table as I mentioned in the README update in the PR. Yes it will have many more functions.

Cool cool. It's always nice to have module names derived from elsewhere.

**Comment by adithyaov** [comment]
Closed by #29
