### ISSUE TITLE
Naming, organization of exposed modules

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/unicode-data#3]
Since exposed modules become public and then need to be maintained, we need to think about how they should be organized and named, and what should be exposed now and what should remain internal. It will depend on who can use this library and in what ways.

**Comment by harendra-kumar** [comment]
We can use naming similar to streamly e.g. use `Unicode.*` instead of `Data.Unicode.*`.

**Comment by harendra-kumar** [comment]
We should make unicode-transforms use this package as a dependency and remove this code from that package.

**Comment by harendra-kumar** [comment]
The module `DecompositionsK.hs` was split into `DecompositionsK.hs` and `DecompositionsK2.hs` because of a big file compilation issue. Not sure if that issue still remains.  Maybe we can export these two modules via a common module, though I am not sure if the issue will reappear if we do that.

**Comment by harendra-kumar** [comment]
Looks like we already include `DecompositionsK2.hs` in `DecompositionsK.hs`, we just need to move `DecompositionsK2.hs` to the Internal module hierarchy.

**Comment by harendra-kumar** [comment]
Have the following exposed modules:

* Unicode.Properties.Core
* Unicode.Properties.CombiningClass
* Unicode.Properties.Compose
* Unicode.Properties.Decompose
* Unicode.Properties.DecomposeHangul

The rest of modules should be moved to `Internal`.

Also rename:

* composePair => compose
* composeStarterPair => composeStarters
* getCombiningClass => combiningClass

Remove the import of `Data.Unicode.Properties.DecomposeHangul` in `Data.Unicode.Properties.Decompose`

Change:

```
data DecomposeMode = Canonical | Kompat
```

**Comment by adithyaov** [comment]
Closed by #1

**Comment by harendra-kumar** [comment]
We need `Unicode.Properties.Compose` module as well.
