### ISSUE TITLE
Add support for Unicode Identifier and Pattern Syntax properties (TR31)

### ISSUE THREAD

**Issue by guhou** [composewell/unicode-data#34]
To support [Unicode Standard Annex #31](https://www.unicode.org/reports/tr31/), additional properties should be added to the generated functions in this package, namely:

*DerivedCoreProperties.txt*

- `Id_Continue`
- `Id_Start`
- `XID_Continue`
- `XID_Start`

*PropList.txt*

- `Pattern_Syntax`
- `Pattern_White_Space`

**Comment by guhou** [comment]
I'm happy to contribute this, but I'm not entirely clear on what is involved to add new properties. It looks like it may involve adding more options to https://github.com/composewell/unicode-data/blob/master/ucd.sh#L56-L65, but I don't know if there are other moving parts that are also needed. Are there any notes on how the code generation works?

**Comment by adithyaov** [comment]
Hi @guhou, `ucd.sh` runs the executable `ucd2haskell`.
I believe I've written the code such that a general property in `DerivedCoreProperties.txt` or `PropList.txt` can be added.
You might want to take a look at how the parsing is done here, https://github.com/composewell/unicode-data/blob/23a8bf550c6313b1112cdf0bbad23d3098c91db2/exe/Parser/Text.hs#L422-L446

Adding the following as `--core-prop` should ideally work,
* Id_Continue
* Id_Start
* XID_Continue
* XID_Start
* Pattern_Syntax
* Pattern_White_Space

It should generate the corresponding properties prefixed by `is` in the corresponding
* Unicode.Internal.Char.PropList
* Unicode.Internal.Char.DerivedCoreProperties

Please let me know if the info above was helpful, or I can attach a small write-up to how the parsing works.

**Comment by adithyaov** [comment]
@guhou Once you add the generated modules, you might want to also add a user-facing module `Unicode.Char.Identifiers`

These user-facing modules would just re-export the generated functions as a convenient API.

Example, https://github.com/composewell/unicode-data/blob/23a8bf550c6313b1112cdf0bbad23d3098c91db2/unicode-data.cabal#L75-L79

**Comment by guhou** [comment]
Thanks for the guidance @adithyaov, it was helpful in understanding the codebase. :) I've opened a PR with the new properties.
