### ISSUE TITLE
Case conversion operations

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/unicode-data#47]
We do not have `toUpper`, `toLower`, `toTitle` operations in unicode-data yet. base package implements these as `Char -> Char` operations, however that does not handle all the cases. In some cases a conversion may result in multiple characters so the general signature should be`Char -> [Char]` or equivalent.

## General representation

[Char] is not ideal because of performance reasons. For example, it cannot be used for stream fusion, it would also not fuse in nested operations (like concat). A general solution would be to use `Char -> Unfold m Char Char` or `Char -> Unfold Identity Char Char`. This representation is amenable to stream fusion. See [Unfold module in streamly](https://github.com/composewell/streamly/blob/5998dd8c419f534372375e40c3b54a9b52b68183/src/Streamly/Internal/Data/Unfold/Type.hs). 

The basic unfold type can be extracted out from streamly into a small module not depending on anything else. This can then possibly be used here to provide efficient implementations of case conversion operations that can be used generally by anyone. Unfolds can be easily converted to a list or it can be used in implementations that depend on stream-fusion, e.g. this could be used in the `text` package as well replacing the text package's case conversion implementation, and also in streamly's unicode module.

Is there any other way to represent these efficiently for general use?

## Compatibility routines

For compatibility with the `base` `Data.Char` module we could potentially provide `toUpper` and `toLower` (`Char -> Char`) in the `Compat` module and provide `toUpperCase` and `toLowerCase` for the general case. This is independent of the discussion about general representation and can be done even today.

**Comment by wismill** [comment]
Some important points:
1. Currently the case conversion results in up to 3 characters (See `SpecialCasing.txt`)
2. Some case conversion are context-dependent (which characters come before or after).
3. Some case conversion are locale-dependent.

Because of 2), `Unfold` seems a reasonable option.

It could also be used to implement _case folding_.

**Comment by wismill** [comment]
@harendra-kumar So if we have:

```haskell
toUpperCase :: (Monad m) => Char -> Unfold m Char Char
```

what does the second type parameter of `Unfold` denote? I think the seed should be the adjacent characters, such as:

```haskell
data CharContext = CharContext (Maybe Char) (Maybe Char)
toUpperCase :: (Monad m) => Char -> Unfold m CharContext Char
```

**Comment by harendra-kumar** [comment]
It would be:

```haskell
toUpperCase :: (Monad m) => Unfold m Char Char
```

`Unfold m a b` generates a stream of `b` from a seed `a`. So `a` would be the character that we want to convert and a sequence of `b` the characters it expands to.

**Comment by wismill** [comment]
Ok, so if the casing may depend on the adjacent characters, it is the internal state that keep track of the adjacent characters?

**Comment by harendra-kumar** [comment]
I did not pay attention to that case. It would be helpful in designing if we know all the specific cases. 

The example above depends on whether the particular character is a last char or not irrespective of what the following character is. Are there cases that depend on it being a first character? Or cases where it depends on the previous or the following char being a specific char?

**Comment by harendra-kumar** [comment]
I found the "Context Specification" table in tr-21 . There are 4 context sensitive cases. Context dependent case conversion may be tricky. One way to represent the generalized case conversion could be:

```haskell
data Context = NoContext | FinalSigma | MoreAbove | AfterSoftDotted | BeforeDot

toUpperCase :: (Monad m) => Unfold m (Char, Context) Char
```

**Comment by wismill** [comment]
The special cases are defined in https://www.unicode.org/Public/14.0.0/ucd/SpecialCasing.txt

> Are there cases that depend on it being a first character?
> Or cases where it depends on the previous or the following char being a specific char?

From my understanding only immediate previous and following characters. Only `U+0345` requires a special treatment:

```
# IMPORTANT-when iota-subscript (0345) is uppercased or titlecased,
#  the result will be incorrect unless the iota-subscript is moved to the end
#  of any sequence of combining marks. Otherwise, the accents will go on the capital iota.
#  This process can be achieved by first transforming the text to NFC before casing.
#  E.g. <alpha><iota_subscript><acute> is uppercased to <ALPHA><acute><IOTA>
```

Some rules depend on the locale.

**Comment by wismill** [comment]
We should check ICU's implementation or other library to get an idea.

We could provide an implementation for `String` to benchmark it and get a first idea of perf.

**Comment by wismill** [comment]
> I found the "Context Specification" table in tr-21 . There are 4 context sensitive cases. Context dependent case conversion may be tricky. One way to represent the generalized case conversion could be:
> 
> ```haskell
> data Context = NoContext | FinalSigma | MoreAbove | AfterSoftDotted | BeforeDot
> ```

The page I linked for `tr21` is [superseded](https://www.unicode.org/reports/tr21/) by notably section 3.13 (see table 3.17), that adds `After_I`. Also negation of some contexts is required. And handling these contexts does no make much sense if we do not handle the locale as well, such as:

```haskell
toUpperCase :: (Monad m) => Unfold m (Char, Locale, Context) Char
```

I checked [ICU4C](https://github.com/unicode-org/icu/blob/main/icu4c/source/common/ucase.cpp), [ICU4J](https://github.com/unicode-org/icu/blob/main/icu4j/main/classes/core/src/com/ibm/icu/impl/CaseMapImpl.java) and I am not sure we can implement it efficiently this way. Moreover proper case conversion is defined in [CLDR](https://github.com/unicode-org/cldr/tree/main/common/transforms) (see files ending with `-Upper`, etc.) and sometimes requires normalization.

I propose we adopt the approach of `text` and provide only special case conversion _without_ context. Full, localized case conversion could be handled in either `unicode-transforms` or a new package that depends on `unicode-transforms`.

cc @Bodigrim @adithyaov

**Comment by wismill** [comment]
Closing, since we are now on par with `text` (see #77).
