### ISSUE TITLE
Add digitToInt and intToDigit ?

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/unicode-data#48]
`Data.Char` has these operations but `Unicode.Char` does not. Should we add these in the `Char.Numeric` module?

@wismill

**Comment by wismill** [comment]
I think yes. And there are also the functions `showLitChar`, `lexLitChar` and `readLitChar` that could be re-exported in `Unicode.Char`. What do you think?

**Comment by harendra-kumar** [comment]
I was a bit unsure about the `*LitChar` stuff, we are probably re-exporting too much in trying to be a drop in replacement. But I won't oppose if others feel this is fine, these are the last remaining ones anyway.

**Comment by wismill** [comment]
I agree these are not mandatory. I am neutral on keeping them out.
