### ISSUE TITLE
Use unicode-data in unicode-transforms

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/unicode-data#5]
Make use of this package in unicode-transforms, run the tests and benchmarks in unicode-transforms to ensure everything is fine. I see one additional INLINE in `isSecondStarter` bitmap, that should be fine, but to be sure we can run unicode-transforms benchmarks. Once this package is uploaded we can merge the unicode-transforms changes.

**Comment by adithyaov** [comment]
See https://github.com/composewell/unicode-transforms/pull/57
