### ISSUE TITLE
Upload unicode-data-0.3 to hackage

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/unicode-data#55]
Thanks to @wismill we have significant functionality committed to the package. We can now upload the new release candidate to hackage.

@wismill what is your hackage id, I will add you to package maintainers so that you can upload it.

We can use this issue as a checklist to do any remaining due diligence required for the release.

**Comment by wismill** [comment]
My hackage ID is wismill.

**Comment by harendra-kumar** [comment]
@adithyaov can you review if the package is ready for release or if there is anything that should be done. I don't think the bench-show based comparison should be a blocker, we can do that later. Mainly, testing, performance, breaking changes, docs, dependencies should be reviewed.

**Comment by adithyaov** [comment]
I went through the release checklist. 

TBD: 

- [ ] Clone the repo into a clean workspace
- [ ] `cabal v2-sdist; cabal upload --publish <tarpath>`
- [ ] Push the new tag

**Comment by harendra-kumar** [comment]
It would be better to not use `--publish` right away so that we can check the candidate before publishing.

**Comment by wismill** [comment]
See: https://hackage.haskell.org/package/unicode-data-0.3.0/candidate

**Comment by harendra-kumar** [comment]
First time after a long time, I saw haddock being generated for a candidate.

https://hackage.haskell.org/package/unicode-data-0.3.0/candidate/docs/Unicode-Char.html - How come case conversion ops are not in the Unicode.Char.Case module?

**Comment by wismill** [comment]
> First time after a long time, I saw haddock being generated for a candidate.

I have uploaded it manually. 

> https://hackage.haskell.org/package/unicode-data-0.3.0/candidate/docs/Unicode-Char.html - How come case conversion ops are not in the Unicode.Char.Case module?

It seems so [by design](https://github.com/haskell/haddock/issues/944#issuecomment-422824455).

**Comment by harendra-kumar** [comment]
Ah, that's because of hiding. Ok, then. Looks good to me.

> I have uploaded it manually.

huh...I was happy that it's fixed, but it's not.

**Comment by wismill** [comment]
Is there anything else to do before the release?

**Comment by harendra-kumar** [comment]
Go ahead and publish it.

**Comment by harendra-kumar** [comment]
Also, if you feel like making an announcement on haskell discourse/reddit or any other forums please do that too. Significant changes have gone in this package, it should be quite useful now, so it may be a good idea to let others know about it.

**Comment by wismill** [comment]
Release done.

> Also, if you feel like making an announcement on haskell discourse/reddit or any other forums please do that too. Significant changes have gone in this package, it should be quite useful now, so it may be a good idea to let others know about it.

Good idea. I will do it soon.

**Comment by wismill** [comment]
Announcement:
- [Discourse](https://discourse.haskell.org/t/ann-unicode-data-0-3-0-apis-to-efficiently-access-the-unicode-character-database)
- [Reddit](https://www.reddit.com/r/haskell/comments/ru7zvv/ann_unicodedata030_apis_to_efficiently_access_the/)

**Comment by harendra-kumar** [comment]
Strangely, reddit removed the post, it says: `Reddit's automated bots frequently filter posts it thinks might be spam.`

**Comment by wismill** [comment]
I already contacted the moderators but got no response

**Comment by harendra-kumar** [comment]
I think it may be likely to be classified as spam if there is only a link and no description.

**Comment by wismill** [comment]
New attempt: [Reddit](https://www.reddit.com/r/haskell/comments/s4hsv4/ann_unicodedata030_apis_to_efficiently_access_the/)
