### ISSUE TITLE
Consider not using Show when making GeneralCategory etc.

### ISSUE THREAD

**Issue by axman6-da** [composewell/unicode-data#61]
GeneralCategory.hs is enormous, but this is the nature of having this sort of lookup table in the code. It can be made quite a lot smaller and hopefully ease the work the compiler has to do parsing it by using the numeric values for the chars in it. replacing the generation of `\EOT` with `\4` saves 254,666 characters in the source file, but also has the benefit that a human can look at the table and tell which category fromEnum value a particular position corresponds to. A quick find and replace of some of the more common characters gives this saving in the line length of bitmap#:

```
    Original     -> 3485166
    EOT replaced -> 3230500
    NUL replaced -> 3226838
    NAK replaced -> 3220233
    SOH replaced -> 3215779
    ENQ replaced -> 3211879
    SUB replaced -> 3211716
    ETX replaced -> 3211048
```

I understand this isn't something people are expected to read very often, but for the times when someone does need to, it would be helpful. I'd even consider adding a generated comment which shows the mapping between the numeric and `GeneralCategory` values.

**Comment by harendra-kumar** [comment]
Sure. Would you care to send a PR in case you have already done this?

**Comment by axman6-da** [comment]
I had a play around and came up with the following diff, sorry it's not a PR:

```diff
diff --git a/exe/Parser/Text.hs b/exe/Parser/Text.hs
index 8b8e1e6..a805b5a 100644
--- a/exe/Parser/Text.hs
+++ b/exe/Parser/Text.hs
@@ -167,8 +167,8 @@ genEnumBitmap funcName as = unlines
                <> show (fromEnum Cn)
                <> " else lookupIntN bitmap# n"
     , "  where"
-    , "    bitmap# = "
-        <> show (enumMapToAddrLiteral as) <> "#"
+    , "    bitmap# = \""
+        <> enumMapToAddrLiteral as "\"#"
     ]
 
 {-| Encode a list of values as a byte map, using their 'Enum' instance.
@@ -178,13 +178,13 @@ __Note:__ 'Enum' instance must respect the following:
 * @fromEnum minBound >= 0x00@
 * @fromEnum maxBound <= 0xff@
 -}
-enumMapToAddrLiteral :: forall a. (Bounded a, Enum a, Show a) => [a] -> String
-enumMapToAddrLiteral = fmap go
+enumMapToAddrLiteral :: forall a. (Bounded a, Enum a, Show a) => [a] -> String -> String
+enumMapToAddrLiteral xs tl = foldr go tl xs
 
     where
 
-    go :: a -> Char
-    go = chr . fromIntegral . toWord8
+    go :: a -> String -> String
+    go a tl' = '\\' : shows (toWord8 a) tl'
 
     toWord8 :: a -> Word8
     toWord8 a = let w = fromEnum a in if 0 <= w && w <= 0xff
```

Which takes the same from `3485793` to `3207915` for saving of `277878` and makes the array a little easier to understand by keeping everything numeric.
