### ISSUE TITLE
Merge unicode-data in base

### ISSUE THREAD

**Issue by wismill** [composewell/unicode-data#62]
There is [interest](https://discourse.haskell.org/t/ann-unicode-data-0-3-0-apis-to-efficiently-access-the-unicode-character-database/3861/14) to merge unicode-data in `base`. In the corresponding [ghc ticket](https://gitlab.haskell.org/ghc/ghc/-/issues/21375), there is a question about re-licensing from Apache 2.0 to BSD-3-Clause for inclusion in GHC.

Side note: it would be great to see this happening, but I think having _also_ an independent package is great to be able to pick a specific Unicode version.

**Comment by Bodigrim** [comment]
Since there was no CLA signed, strictly speaking we need an explicit agreement from all contributors, which are @harendra-kumar @adithyaov @wismill @guhou @Bodigrim. 

I agree to relicense from Apache 2.0 to BSD-3-Clause.

**Comment by wismill** [comment]
I agree to relicense from Apache 2.0 to BSD-3-Clause.

**Comment by adithyaov** [comment]
I agree to relicense from Apache 2.0 to BSD-3-Clause.

**Comment by harendra-kumar** [comment]
I agree to use BSD-3-Clause license for all contributions from me and from Composewell Technologies to this repository.

**Comment by nomeata** [comment]
>  having also an independent package is great to be able to pick a specific Unicode version.

No objections at all; I’m sure we can keep that in mind (by using different module names in `base`, or simply not exposing any of the advanced functionality in base)

**Comment by guhou** [comment]
Hi folks, sorry for the slow response.

I agree to relicense from Apache 2.0 to BSD-3-Clause.

**Comment by wismill** [comment]
I started a [MR for GHC](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8072).

**Comment by askeblad** [comment]
@harendra-kumar 

A sole typo in the repository is rendered below.

```sh
$ grep -n correspong unicode-data/exe/Parser/Text.hs
680:        _ -> error $ "Cannot create range: missing <range, Last> entry correspong to: " <> show range1
$ 
```

**Comment by harendra-kumar** [comment]
Thanks for finding and reporting @askeblad .

**Comment by askeblad** [comment]
Some [preliminary](https://gitlab.haskell.org/ghc/ghc/-/issues/21520) work for a base MR.

**Comment by wismill** [comment]
[Merged](https://gitlab.haskell.org/ghc/ghc/-/commit/ef7ddd7348070a9149d162217280c0a50f2b213d)
