### ISSUE TITLE
Support Name and NameAlias properties

### ISSUE THREAD

**Issue by pxeger** [composewell/unicode-data#67]
There are two properties here:

"Name", which gives each assigned character exactly one name. This maps, for example, `'a'` -> `"LATIN SMALL LETTER A"``.
The data for this are in https://www.unicode.org/Public/14.0.0/ucd/UnicodeData.txt, and also extracted into https://www.unicode.org/Public/14.0.0/ucd/extracted/DerivedName.txt. Ideally, there would be an API both to map characters to their names, and string names to the characters they represent.

"NameAlias", which assigns some additional names for certain characters; for example, `ZWJ` for `ZERO WIDTH JOINER`. The data are in https://www.unicode.org/Public/14.0.0/ucd/NameAliases.txt. Only an API from string alias to character is needed.

**Comment by wismill** [comment]
I thought about this but wouldn’t it increase a lot the size of the library? If so, maybe we should then create a separate library (`unicode-data-names` ?).

@harendra-kumar @adithyaov any thoughts?

**Comment by harendra-kumar** [comment]
Yes, even the existing GeneralCategory.hs file is quite big. Things that are less used but have a big database can go to auxiliary packages.

**Comment by wismill** [comment]
@harendra-kumar `unicode-data-names` [candidate](https://hackage.haskell.org/package/unicode-data-names-0.1.0/candidate) is available on Hackage.

**Comment by harendra-kumar** [comment]
Great work @wismill ! I looked at the candidate and it looks fine.

**Comment by wismill** [comment]
[`unicode-data-names 0.1.0`](https://hackage.haskell.org/package/unicode-data-names-0.1.0) published!

**Comment by pxeger** [comment]
Awesome, thanks everyone!
