### ISSUE TITLE
Support `NumericValue` property

### ISSUE THREAD

**Issue by pxeger** [composewell/unicode-data#68]
This maps, for example, `𝟜` and `௪` to the number 4, or `⅐` to 0.14285714. It would need to return a `Double`, because not all characters have integral values. There could perhaps be a second API optimised for integral values.

The data are in https://www.unicode.org/Public/14.0.0/ucd/extracted/DerivedNumericValues.txt, which has been extracted from https://www.unicode.org/Public/14.0.0/ucd/UnicodeData.txt

**Comment by wismill** [comment]
It makes sense to have a `Rational` for all of them and an `Int` variant for integers.
