### ISSUE TITLE
Enable tests in CIs

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/unicode-data#79]
Tests are disabled in the CI config.

Even when I tried to run tests locally, it said:

```
cabal test all
cabal: Cannot test all the packages in the project because none of the
components are available to build: the test suite 'test' and the test suite
'test' are not available because the solver did not find a plan that included
the test suites. Force the solver to enable this for all packages by adding
the line 'tests: True' to the 'cabal.project.local' file.
```

Not good.

**Comment by wismill** [comment]
As of a0b321e039a4049a4636f356ac11051b2d4feaae, is it solved?

> Tests are disabled in the CI config.
> 
> Even when I tried to run tests locally, it said:
> 
> ```
> cabal test all
> cabal: Cannot test all the packages in the project because none of the
> components are available to build: the test suite 'test' and the test suite
> 'test' are not available because the solver did not find a plan that included
> the test suites. Force the solver to enable this for all packages by adding
> the line 'tests: True' to the 'cabal.project.local' file.
> ```
> 
> Not good.

I have no issue running this command locally (cabal 3.8, ghc 9.2.4).

**Comment by harendra-kumar** [comment]
Yes, it is working now.
